appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: Q/nwK31fDcacseSfl/eUJruDW8lgjGmAh6M7kl3gCVhz+QnV/kRHLpbA1LMTh/nz9WHT0xq8DFWCWz7QpVS9HzyoZgRb2naxnh1ixrFIPlTzIt12uMc/QgxW0o9YZ7PuwoLfEBBlKBpmUOoEpCI026dSGdkuRvROAq/uAHaI1ckXznKPTT0IYK0XGxAaM36necFPYMU95Lw51W6smJ9q6kcM/PNf7S+Thcqa84AzzIYOus3QT/iiX0E+HRtOKnMC8eIbsuyBa17RKjLwSl0ApeOGtaSUScJ/BrUbQpgL+s3mKvzQQIKgEXgzSNvm/oqzGwZ2V8wrwZKuNVery71CSpYCdMibNWL2ayN3up4Tob+jwtX6oEIdsCPcrtsmPYWBjyeSVhJ6OePxhBX0L7jBYXDHlplrcDSyfH3wahH8n4HkINzn1ywMDDdubriQuUoYw8ANBUOh5XuB74QwBrWxftm069R9BhDViAgwvmGLFeBbJfpSnBCL8ctkH3pWHGE3CG0Ot8H6uM3YfD6rSWLBuZ2GlPZP7RePTbS9i7BsGN7rI4725mjuCKQ7UUw+8ezyA6kkhkJgA0rCc7tPL/NNk1IlyPFN8Kxh6+Q8gNp9liq1vKZeWmJDXCSIAzvyY/8rMYTGK1DX2KpDAcBYVFejlk8HrSWLbkkrv6oVXryso2w=
conda_forge_output_validation: true
