travis:
  secure:
    BINSTAR_TOKEN: UCauosvgpt30nILp7V+JCnmEm3a+JN12VwpOv94EVZT03qZrqoVqrOCAuJLeUMBHZPcKCq0/CN1tsVZjI4TSjNBf9bB0fqykcExGHo8Na0/AWHYi+8RNrnZlwFXg6uMYUVJY7boK9kVF9GcThKn9GN3n/VPzYhL2b/TbBeOXF9cGV0sYu9kGWy+ng9bctXohGs/UjGsD7hlbTLW9klGuYpqMMYhQlb4dvzJzhrteqIiZkneHNvuUnCJxTAZncRuWroEgihhComwgqKlEZztW18JuTkVu6fdG5y00Ab4QrG2IHYJVc9VZkHObNGLbFUx7FFdU3oJOiAfSB4a9ahd/1U8r7jmNwnGMbZRXSr5WBB3mYYYTOJvljnvRI9sk3FH2IFlxOGp3FS+vhZOOnJyMeZPbfuDG0dYPOODijGMD26gkjJDRRyhFw1EkTWssaBi7tLD8PfgJNpir96osNNKGD3Ld4nixUwfFXv32W9PtwFHpTK/sADk5CADbnlszyM1OS/vWgT+gKEFnQOjlbHqyHNKC26cIvm2OY18NB2UsEZCpmmt0D1U99pJmHi2L/EZuT9eLqwKNpQQq+2oeqgcSEjeqGhHIEXc/by5LtqVtYWz6pWiYBtAS5D3sAkHE9gkM9L/Kn6LtKfDZkRo/qfAbXBqjDtxpWK2yqcnKjSjUY+A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
