travis:
  secure:
    BINSTAR_TOKEN: L+JFXDZvgjG184jjCPR0hmvvF8hIXwyTWd36vVPvZJlKDATZjLyigKG/1WkRqn9dWyo0vT2V7orzCl95IxP6HTArwALZ1pr2bS04VvCn+Z+j+jLqXgT8FiHFEM6T6L2z7Ss3akB6RqsNMMK2KLjeG7n/mVbpL6YCTaE4ysi2UW5/+PMT1KhFnz4x2sYAB/GzaBxvggQROsL6ALF7s8q3K5es/a3WlqGv1PCIPCbqZxfRyvQkiikIksZ63fDd1V/Cc3H1+ZCxe5OQmlP0apXCfbQ8tblwZtuCgHNzxgBetZKi44YwAR3xHRVHBa2kGz8ZzAFdxppK2eGzPPA2zVKbONoTwIuOGog0RZEE83TVqNDnX6wkOf/yzeOs/R4An4fQklH//KvM0sUMuQ9qwvJmHNUqvimOLQLJLHvctWsiFbOSX1uDKxx3KmvlLmYQCEnjF/yiPM/61dU/tHki9kSgdK6BvslfnfWlHbpPenAKXEwE+P59YNSkslRvehH30WUTD+lJB/RxFgid4R693st2iJdqHf/KUDtGmlsF9xE3bpnK19wpaATnuECXXzhhp4Eeh7Sb4eUwa7I2PF6zT+MGZX0NHJVs7+/2DspHWPw74FUiUAZglaAsTsM9GFYUSEVN1bwxiir1oJKKMw92/6rcnmmw6WVBr5Ze70SD/pqfzFU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
