travis:
  secure:
    BINSTAR_TOKEN: TED31czd1wwn/kBuGskw3C3XDAfN+H6aZrGh82Q6qZJmswvO8ONy2WAqKTt7C40Dp2hJd8Fvjub6t8apbiJmTW88nE1LcqDPFbrgc6csWb7nBZTJlrWWHyIsIDCkJ/kKU2ZuGAziHpyfsmwCOGdh4nXKz11qMnuianDShs4cP66GATzZ5EQE5BWyDp88QaDD4XG5kjXk88IGyYpDgfkk3E4yHvZk9TCkzZEjfXmP8PPkjOddpwcmTjAKdVTz1hpL2b+vf9uG5afoEFwMYmHw7vLiJ7BBw4M2oYjEcgpUMMNi2AQAPE0sHHtO92V36dWuNlpdPKh7ttublDwa06rMOGONHu5pgbC5/vDA74aC+Jk/BZN36AFkVQNEsbop08ZZYZNbZbX/8UC2WPDnmBnnFJVilQcVjNVYzTjU39im02ZE/HuVB2YCVnyZJC7ssh6KSB6kFJThY6ITJQHyVjGDdoHat/7WOzmK3i0+5ZyeQgs8SmZ2sYRHucc5nWOji+Zxj8FMp0dSg8N1DgW51TkfaaNMuyP341Z8rz5vFebJCLXVrRiUU77c43SJXYqhfivfsztYHzvM1pLqRAjU6w1qLfeDs+/Evdfb2wGrZUcy5nQnTLhjyFZ6kr/Gvrs331uTcT8ZcHRq5wlianMZK8hMvj48Jx+FFLVKDtwLTHyZUag=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
